server:
  # 配置项目端口
  port: 20000
# spring相关配置
spring:
  #数据源配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ai_ks?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&
# web-starter相关配置
suhuamo:
  web:
    mybatis:
      # 生成的包路径，同时也是项目的父目录
      parent: com.yscz.test
      # 需要自动生成代码的数据库表
      tables:
        - t_student
      # 生成代码时的java类去掉前缀，可为空
      tablePrefix:
        - t_